/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Int,
  'service' : IDL.Text,
  'afterImage' : ExternalBlob,
  'beforeImage' : ExternalBlob,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const Testimonial = IDL.Record({
  'id' : IDL.Int,
  'service' : IDL.Text,
  'customerName' : IDL.Text,
  'text' : IDL.Text,
  'rating' : IDL.Int,
  'image' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'id' : IDL.Int,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const HomepageContent = IDL.Record({
  'heroSubtitle' : IDL.Text,
  'heroImage' : IDL.Opt(ExternalBlob),
  'ctaText' : IDL.Text,
  'aboutText' : IDL.Text,
  'heroTitle' : IDL.Text,
});
export const SiteTheme = IDL.Record({
  'backgroundColor' : IDL.Text,
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryImage' : IDL.Func([GalleryImage], [], []),
  'addService' : IDL.Func([IDL.Text, Service], [], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBookingRequests' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHomepageContent' : IDL.Func([], [HomepageContent], ['query']),
  'getService' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
  'getSiteTheme' : IDL.Func([], [SiteTheme], ['query']),
  'getTestimonialsByRating' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeGalleryImage' : IDL.Func([IDL.Int], [], []),
  'removeService' : IDL.Func([IDL.Text], [], []),
  'removeTestimonial' : IDL.Func([IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSiteTheme' : IDL.Func([SiteTheme], [], []),
  'submitBookingRequest' : IDL.Func([BookingRequest], [IDL.Int], []),
  'updateGalleryImage' : IDL.Func([GalleryImage], [], []),
  'updateHomepageContent' : IDL.Func([HomepageContent], [], []),
  'updateService' : IDL.Func([IDL.Text, Service], [], []),
  'updateTestimonial' : IDL.Func([Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Int,
    'service' : IDL.Text,
    'afterImage' : ExternalBlob,
    'beforeImage' : ExternalBlob,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Int,
    'service' : IDL.Text,
    'customerName' : IDL.Text,
    'text' : IDL.Text,
    'rating' : IDL.Int,
    'image' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'id' : IDL.Int,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const HomepageContent = IDL.Record({
    'heroSubtitle' : IDL.Text,
    'heroImage' : IDL.Opt(ExternalBlob),
    'ctaText' : IDL.Text,
    'aboutText' : IDL.Text,
    'heroTitle' : IDL.Text,
  });
  const SiteTheme = IDL.Record({
    'backgroundColor' : IDL.Text,
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryImage' : IDL.Func([GalleryImage], [], []),
    'addService' : IDL.Func([IDL.Text, Service], [], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBookingRequests' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHomepageContent' : IDL.Func([], [HomepageContent], ['query']),
    'getService' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
    'getSiteTheme' : IDL.Func([], [SiteTheme], ['query']),
    'getTestimonialsByRating' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeGalleryImage' : IDL.Func([IDL.Int], [], []),
    'removeService' : IDL.Func([IDL.Text], [], []),
    'removeTestimonial' : IDL.Func([IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSiteTheme' : IDL.Func([SiteTheme], [], []),
    'submitBookingRequest' : IDL.Func([BookingRequest], [IDL.Int], []),
    'updateGalleryImage' : IDL.Func([GalleryImage], [], []),
    'updateHomepageContent' : IDL.Func([HomepageContent], [], []),
    'updateService' : IDL.Func([IDL.Text, Service], [], []),
    'updateTestimonial' : IDL.Func([Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };