/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : bigint,
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'phone' : string,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : bigint,
  'service' : string,
  'afterImage' : ExternalBlob,
  'beforeImage' : ExternalBlob,
  'description' : string,
  'location' : string,
}
export interface HomepageContent {
  'heroSubtitle' : string,
  'heroImage' : [] | [ExternalBlob],
  'ctaText' : string,
  'aboutText' : string,
  'heroTitle' : string,
}
export interface Service {
  'id' : string,
  'title' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
}
export interface Testimonial {
  'id' : bigint,
  'service' : string,
  'customerName' : string,
  'text' : string,
  'rating' : bigint,
  'image' : [] | [ExternalBlob],
  'location' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'addService' : ActorMethod<[string, Service], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHomepageContent' : ActorMethod<[], HomepageContent>,
  'getService' : ActorMethod<[string], [] | [Service]>,
  'getTestimonialsByRating' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeGalleryImage' : ActorMethod<[bigint], undefined>,
  'removeService' : ActorMethod<[string], undefined>,
  'removeTestimonial' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBookingRequest' : ActorMethod<[BookingRequest], bigint>,
  'updateGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'updateHomepageContent' : ActorMethod<[HomepageContent], undefined>,
  'updateService' : ActorMethod<[string, Service], undefined>,
  'updateTestimonial' : ActorMethod<[Testimonial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];